/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SellRouteImport } from './routes/sell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as AuctionIndexRouteImport } from './routes/auction.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InventoryIdRouteImport } from './routes/inventory.$id'
import { Route as AdminCreateRouteImport } from './routes/admin.create'
import { Route as AdminIdRouteImport } from './routes/admin.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const AuctionIndexRoute = AuctionIndexRouteImport.update({
  id: '/auction/',
  path: '/auction/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InventoryRoute,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/contact': typeof ContactRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/create': typeof AdminCreateRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auction/': typeof AuctionIndexRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/create': typeof AdminCreateRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/admin': typeof AdminIndexRoute
  '/auction': typeof AuctionIndexRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/contact': typeof ContactRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/create': typeof AdminCreateRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auction/': typeof AuctionIndexRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth-callback'
    | '/contact'
    | '/inventory'
    | '/login'
    | '/sell'
    | '/services'
    | '/terms'
    | '/admin/$id'
    | '/admin/create'
    | '/inventory/$id'
    | '/admin/'
    | '/auction/'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth-callback'
    | '/contact'
    | '/login'
    | '/sell'
    | '/services'
    | '/terms'
    | '/admin/$id'
    | '/admin/create'
    | '/inventory/$id'
    | '/admin'
    | '/auction'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth-callback'
    | '/contact'
    | '/inventory'
    | '/login'
    | '/sell'
    | '/services'
    | '/terms'
    | '/admin/$id'
    | '/admin/create'
    | '/inventory/$id'
    | '/admin/'
    | '/auction/'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ContactRoute: typeof ContactRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  SellRoute: typeof SellRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  AuctionIndexRoute: typeof AuctionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/auction/': {
      id: '/auction/'
      path: '/auction'
      fullPath: '/auction/'
      preLoaderRoute: typeof AuctionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/inventory/$id': {
      id: '/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIdRoute: typeof AdminIdRoute
  AdminCreateRoute: typeof AdminCreateRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIdRoute: AdminIdRoute,
  AdminCreateRoute: AdminCreateRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InventoryRouteChildren {
  InventoryIdRoute: typeof InventoryIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryIdRoute: InventoryIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ContactRoute: ContactRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  SellRoute: SellRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  AuctionIndexRoute: AuctionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
